import type { Finding, FindingCategory, Severity } from './types';
type Rule = { id: string; severity: Severity; category: FindingCategory; title: string; pattern: RegExp; remediation: string };
const rules: Rule[] = [
  { id: 'SKILL001', severity: 'high', category: 'prompt-injection', title: 'Attempts to override agent instructions', pattern: /ignore\s+(?:all\s+)?previous\s+instructions|system\s+message\s*:/i, remediation: 'Treat this text as untrusted data and keep system/developer instructions authoritative.' },
  { id: 'CMD001', severity: 'high', category: 'command-execution', title: 'Destructive or remote shell execution', pattern: /(?:curl|wget|Invoke-WebRequest)[^\n]*(?:\||;|&&)\s*(?:sh|bash|iex)|\brm\s+-rf\b|\bchmod\s+\+x\b/i, remediation: 'Require explicit user approval, pin the source, and run commands inside a sandbox with least privilege.' },
  { id: 'CRED001', severity: 'high', category: 'credential-access', title: 'Credential or private-key access', pattern: /(?:BEGIN [A-Z ]*PRIVATE KEY|(?:aws_access_key_id|api[_ -]?key|github_token|\.ssh\/|\.aws\/credentials))/i, remediation: 'Remove credential access from the skill and use scoped, injected secrets only when strictly necessary.' },
  { id: 'EXFIL001', severity: 'high', category: 'data-exfiltration', title: 'Potential outbound data transfer', pattern: /(?:curl|wget)[^\n]*(?:-X\s*POST|-d\s|--data|webhook|upload)|(?:requests?\.(?:post|put)|fetch\s*\()[^\n]*(?:webhook|upload|POST|https?:\/\/)/i, remediation: 'Review the destination and payload; block network access by default for untrusted skills.' },
  { id: 'MCP001', severity: 'medium', category: 'mcp-config', title: 'Unpinned package execution in MCP config', pattern: /\bnpx\s+(?!-[^\n]*\s)(@[\w.-]+\/)?[\w.-]+(?!@[\d])/i, remediation: 'Pin the exact package version and verify its integrity before installation.' },
  { id: 'MCP002', severity: 'medium', category: 'mcp-config', title: 'Broad or unrestricted tool permission', pattern: /(?:allowedTools|permissions|tools)\s*[:=][^\n]*(?:\*|all|任意)/i, remediation: 'Replace wildcard permissions with an explicit allowlist of required tools.' },
  { id: 'OBF001', severity: 'medium', category: 'obfuscation', title: 'Obfuscation or dynamic evaluation', pattern: /(?:base64\s*(?:-d|decode)|atob\s*\(|eval\s*\(|fromCharCode)/i, remediation: 'Prefer readable code and explain any encoding; prohibit dynamic evaluation in untrusted skills.' },
  { id: 'UNICODE001', severity: 'low', category: 'obfuscation', title: 'Hidden Unicode control characters', pattern: /[\u202A-\u202E\u2066-\u2069\u200B\u200C\u200D\uFEFF]/, remediation: 'Remove invisible directional or zero-width characters and inspect the normalized text.' }
];
const weights: Record<Severity, number> = { info: 1, low: 5, medium: 15, high: 30 };
export function scanLines(text: string): Finding[] { const findings: Finding[] = []; text.split(/\r?\n/).forEach((line, index) => { for (const rule of rules) { rule.pattern.lastIndex = 0; if (rule.pattern.test(line)) findings.push({ ruleId: rule.id, severity: rule.severity, category: rule.category, title: rule.title, line: index + 1, evidence: line.trim().slice(0, 240), remediation: rule.remediation }); } }); return findings; }
export function scoreFindings(findings: Finding[]): number { return Math.min(100, findings.reduce((total, finding) => total + weights[finding.severity], 0)); }
